import Content.B05_Geometry.chapters.CS6501_Rational2D

open Content.B05_Geometry.chapters.rationalVectorSpace

/-- Build a demonstration scene: a triangle with midpoints,
    displacement vectors, and points along a parametric line. -/
def scene : String :=
  -- Three vertices of a triangle
  let a : RPoint2 := ⟨0, 0⟩
  let b : RPoint2 := ⟨4, 0⟩
  let c : RPoint2 := ⟨1, 3⟩

  -- Midpoints of each edge
  let mab := midpoint2d a b
  let mbc := midpoint2d b c
  let mac := midpoint2d a c

  -- Displacement vectors from A
  let vab : RVec2 := b -ᵥ a
  let vac : RVec2 := c -ᵥ a

  -- Interior points along the parametric line from A to C
  let lerps := [1/4, 1/3, 2/3, 3/4].map fun t =>
    pointToJson s!"t={ratToJson t}" (affineInterp2d a c t)

  let items : List String := [
    pointToJson "A" a,
    pointToJson "B" b,
    pointToJson "C" c,

    pointToJson "mid(A,B)" mab,
    pointToJson "mid(B,C)" mbc,
    pointToJson "mid(A,C)" mac,

    vectorToJson "B - A" a vab,
    vectorToJson "C - A" a vac,

    segmentToJson "AB" a b,
    segmentToJson "BC" b c,
    segmentToJson "CA" c a,

    segmentToJson "medial" mab mbc,
    segmentToJson "medial" mbc mac,
    segmentToJson "medial" mac mab
  ] ++ lerps

  toJsonArray items

/-- Make a list of points by repeatedly applying a step function. -/
def iteratePoints (n : Nat) (step : RPoint2 → RPoint2) (start : RPoint2) : List RPoint2 :=
  match n with
  | 0 => [start]
  | Nat.succ n' => start :: iteratePoints n' step (step start)

/-- Label points as T0, T1, ... or M0, M1, ... -/
def labeledPointsAux (tag : String) : Nat → List RPoint2 → List String
  | _, [] => []
  | i, p :: ps =>
      pointToJson s!"{tag}{i}" p :: labeledPointsAux tag (i + 1) ps

def labeledPoints (tag : String) (pts : List RPoint2) : List String :=
  labeledPointsAux tag 0 pts

/-- Connect consecutive points with segments. -/
def pathSegments (label : String) : List RPoint2 → List String
  | p1 :: p2 :: ps =>
      segmentToJson label p1 p2 :: pathSegments label (p2 :: ps)
  | _ => []

/-- Draw a segment from each missile position to the corresponding target position. -/
def gapSegments : List RPoint2 → List RPoint2 → List String
  | m :: ms, t :: ts =>
      segmentToJson "gap" m t :: gapSegments ms ts
  | _, _ => []

/-- Missile positions generated by chasing the target list.
    Each step, the missile moves partway toward the current target point. -/
def missilePathFromTargets (targets : List RPoint2) (k : Rat) (m0 : RPoint2) : List RPoint2 :=
  let rec go (ts : List RPoint2) (m : RPoint2) : List RPoint2 :=
    match ts with
    | [] => []
    | t :: ts' =>
        m :: go ts' (affineInterp2d m t k)
  go targets m0

/-- Simple 2D missile/target pursuit scene. -/
def scene1 : String :=
  -- Initial positions
  let targetStart : RPoint2 := ⟨8, 6⟩
  let missileStart : RPoint2 := ⟨0, 0⟩

  -- Constant target velocity
  let targetVel : RVec2 := ⟨1, 1/2⟩

  -- Number of time steps
  let steps : Nat := 8

  -- How aggressively the missile chases the target
  let chaseFrac : Rat := 1/3

  -- Target path: repeated translation by the same vector
  let targetPts : List RPoint2 :=
    iteratePoints steps (fun p => targetVel +ᵥ p) targetStart

  -- Missile path: repeated affine move toward the target
  let missilePts : List RPoint2 :=
    missilePathFromTargets targetPts chaseFrac missileStart

  let items : List String :=
    [
      pointToJson "TargetStart" targetStart,
      pointToJson "MissileStart" missileStart,
      vectorToJson "target velocity" targetStart targetVel
    ]
    ++ labeledPoints "T" targetPts
    ++ labeledPoints "M" missilePts
    ++ pathSegments "target path" targetPts
    ++ pathSegments "missile path" missilePts
    ++ gapSegments missilePts targetPts

  toJsonArray items

def main : IO Unit := do
  IO.println scene1
